### ISSUE TITLE
Unable to use hooks.

### ISSUE THREAD

**Issue by arslanakhtar61** [BotEngineAI/chat-widget#1]
Hi. I am trying to use the hooks provided in my reactJS App but it seems that my variable BE_API is always empty and is unable to hook to that chatbot. I am using a react component with html <iframe /> to load the chatbot widget.

The chatbot loads successfully but it seems that the BE_API doesn't hook properly and hence non of the methods e.g .onLoad gets invoked. Please help
```javascript
class ChatBox extends Component {
    componentDidMount(){
        let BE_API = window.BE_API || {}; //This is always equal to {} why???
        BE_API.onLoad = function () {
            window.alert('chatbot'); //This function body never gets called
            BE_API.openChat();
        };

        BE_API.onLoad = function () {
            setTimeout(function () {
                console.log('2chatbot resetting session');  //This function body never gets called
                // BE_API.resetSession();
                BE_API.openChat();
            },100);
        }    
    }
    render(){
        const { classes, src} = this.props;
        return(
            <div className={classes.card}>
                <iframe 
                    className={classes.media} 
                    src={src}>
                </iframe>
            </div>
        );
    }
 } 
```

**Comment by hstaniszewski** [comment]
I have just simplified the examples of using Chat Widget JS API.

Below is a link with an example of use in React. To make this example work use the ID of your chat widget in line 4 of the example javascript code.

https://jsfiddle.net/6Lpxkwjf/
